### ISSUE TITLE
todos are not adding via add modal add button

### ISSUE THREAD

**Issue by aboutaleb-dev** [VhugoJc/To-Do-Frontend#1]
Hello when I want to add todo I fill the todo fields and then when I click on add button nothing happeneds
I think we should have a server running for this app to run right?

**Comment by VhugoJc** [comment]
Hey @aboutaleb-dev thank you for your comments. 
The main idea of the project is using a backend server to make all the business logic.  So, if you are using only the frontend it won't work. I updated the readme file where I mentioned this.
The backend server is built with spring boot and the repository is https://github.com/VhugoJc/To-Do-Backend. 
Let me know if I can do any more,
